import streamlit as st
from streamlit_float import *

#floatnav
# initialize float feature/capability
float_init()

col1, col2 = st.columns(2)

# 본문
with col1:
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    st.write("This entire column is fixed/floatingsdfsdfs")
    # float_parent()

#고정 사이드바
with col2:
    container = st.container()
    # Fix/float a single container inside
    with container:
        st.write("목차")
        st.write("목차")
        st.write("목차")

        float_parent()
